name: my-second-action
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
        
jobs:
  setup-python-hello-job:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        # 整数计算1+1的值，写入output.log文件中
        run: |
          expr 1 + 1 > output.log
      - name: Upload output file
        # 使用上传制品的action，把刚刚生成的output.log上传
        uses: actions/upload-artifact@v3
        with:
          name: output-log-file
          path: output.log
  load-load-job:
    needs: setup-python-hello-job
    runs-on: ubuntu-latest
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: output-log-file
