# This is a basic workflow to help you get started with Actions

name: called-flow

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    
    secrets:
      FIRST_SECRET:
        required: true
        description: 'The FIRST_SECRET passed from the caller workflow'
        
    # 映射job的变量，到workflow的变量
    outputs:
      output1:
        description: "The first job output"
        value: ${{ jobs.called-job1.outputs.output1 }}
      output2:
        description: "The second job output"
        value: ${{ jobs.called-job1.outputs.output2 }}
      output3:
        description: "The third job output"
        value: ${{ jobs.called-job2.outputs.output1 }}
jobs:
  called-job1:
    runs-on: ubuntu-latest
    # 定义job的输出，workflow_call输出会映射，作为workflow的输出
    outputs:
      output1: called job output1
      output2: called job output2
    steps:
      # 引用secrets中的变量
      - name: called-step
        run: |
          echo ${{ inputs.username }}
  called-job2:
    runs-on: ubuntu-latest
    outputs:
      output1: called job2 output1
    steps:
      - run: |
          echo called job2 step: do sth else
          
    
