name: caller
on: [workflow_dispatch, push]

jobs:
  call-job:
    uses: mollymolly233/mollymolly233/.github/workflows/reusable-workflow-called.yml@main
    with: 
      username: mona
    secrets:
      FIRST_SECRET: ${{ secrets.FIRST_SECRET }}
  
  echo-job:
    runs-on: ubuntu-latest
    needs: call-job
    steps:
      - run: |
          echo ${{ needs.call-job.outputs.output1 }}
          echo ${{ needs.call-job.outputs.output2 }}
    
