# This is a basic workflow to help you get started with Actions

name: reusable-workflow-caller

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  call-reusable-workflow:
    uses: mollymolly233/mollymolly233/.github/workflows/reusable-workflow.yml@main
    with: 
      username: mona
    secrets:
      FIRST_SECRET: ${{ secrets.FIRST_SECRET }}
  
  echo-outputs:
    runs-on: ubuntu-latest
    needs: call-reusable-workflow
    steps:
      - run: |
          echo ${{ needs.call-reusable-workflow.outputs.output1 }}
          echo ${{ needs.call-reusable-workflow.outputs.output2 }}
    
