# This is a basic workflow to help you get started with Actions

name: reusable-workflow-caller

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  call-reusable-workflow:
    uses: mollymolly233/mollymolly233/.github/workflows/reusable-workflow.yml@main
    with: 
      username: mona
    secrets:
      envPAT: ${{ secrets.FIRST_SECRET }}
