# This is a basic workflow to help you get started with Actions

name: called-flow

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    
    secrets:
      FIRST_SECRET:
        required: true
        description: 'The FIRST_SECRET passed from the caller workflow'
        
    # Map the workflow outputs to job outputs
    outputs:
      output1:
        description: "The first job output"
        value: ${{ jobs.called-jobs.outputs.output1 }}
      output2:
        description: "The second job output"
        value: ${{ jobs.called-jobs.outputs.output2 }}

jobs:
  called-jobs:
    runs-on: ubuntu-latest
    # 定义job的输出，workflow_call输出会映射，作为workflow的输出
    outputs:
      output1: called job output 1
      output2: called job output 2
    steps:
      # 引用secrets中的变量
      - name: called-step
        run: |
          echo ${{ inputs.username }}
